#!/bin/sh

auto_mount(){
	if [ "$my_fstype" = 'ntfs' ]; then
		[ -n "$mountpoint" ] && {
			umount $mountpoint
			if [ "$?" -ne 0 ];then
				sleep 2
				umount $mountpoint
			fi
		}

		[ -z "$mountpoint" ] && {
			mount -t ntfs  /dev/$device $mountpath -o rw,noatime,big_writes,iocharset=utf8
		}
	else
		[ -z "$mountpoint" ] && {
			case "$my_fstype" in
				ext*)
					mount -o noatime /dev/$device $mountpath
				;;
				'exfat')
					mount -o noatime /dev/$device $mountpath
				;;
				'vfat')
					uci set fstab.${section}.options="iocharset=utf8,umask=0000,dmask=0000,fmask=0000"
					mount -o iocharset=utf8,umask=0000,dmask=0000,fmask=0000 dev/$device $mountpath
				;;
				*)
					logger -t Auto-Mount "New block.File system:${my_fstype} is not supported, please mount it manually."
				;;
			esac
		}
	fi
}

mountpoint=`sed -ne "s|^[^ ]*/sd[a-z] ||; T; s/ .*//p" /proc/self/mounts`
mountpath="/mnt/shares"

case "$ACTION" in
	add)
		devices="`ls /dev/sd[a-z]`"
		for device in $devices
		do
			my_fstype="`block info | grep "$device" | awk -F 'TYPE="' '{print $2}' | sed 's/\"//'`"
			[ -n "$my_fstype" ] && {
				logger -t Auto-Mount "New block.File system:${my_fstype}"
				[ ! -d "$mountpath" ] && mkdir -p $mountpath
				auto_mount
			}
			judge_ifmount=`sed -ne "s|^[^ ]*/sd[a-z] ||; T; s/ .*//p" /proc/self/mounts`
			if [ -z "$judge_ifmount" ]; then
				logger -t Auto-Mount "New block.File system:${my_fstype} has mounted failed."
			else
				logger -t Auto-Mount "New ${my_fstype} disk has been mounted to \"/mnt/${mountpath}\""
			fi
		done
	;;
esac		
